# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://forge.herow.io/pub/Specs'
target 'testNotifications' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "HerowLocationDetection", '~> 5.2.1'
  # Pods for testNotifications
post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |configuration|
                configuration.build_settings['SWIFT_VERSION'] = "5.0"
                configuration.build_settings['SUPPORTS_UIKITFORMAC'] = 'NO'
                configuration.build_settings['SUPPORTS_MACCATALYST'] = 'NO'
            end
        end
    end

end
