source 'https://github.com/CocoaPods/Specs.git'
source 'https://forge.herow.io/pub/Specs'

platform :ios, '9.0'

target 'Notification' do
    use_frameworks!

    pod 'HerowLocationDetection', '5.2.1'
    
  	post_install do |installer|
          installer.pods_project.targets.each do |target|
              target.build_configurations.each do |configuration|
 	      configuration.build_settings['SWIFT_VERSION'] = "5.0"
              configuration.build_settings['SUPPORTS_UIKITFORMAC'] = 'NO'
              configuration.build_settings['SUPPORTS_MACCATALYST'] = 'NO'
              end
          end
      end
	    
    target 'NotificationTests' do
        inherit! :search_paths
    end
    
    target 'NotificationUITests' do
        inherit! :search_paths
    end
end
